### ISSUE TITLE
Timeslice operator

### ISSUE THREAD

**Issue by rcoh** [rcoh/angle-grinder#10]
See https://github.com/rcoh/angle-grinder/commit/274d34233bec9fd78ae680651efa58ad13b2a2e0 for a template
A non trivial undertaking. My suggested path:
- [ ] Add a `date` subtype to `data::Value` -- this will include the date rendering logic
- [ ] Add a parseDate expression that produces a `date` value from a string
- [ ] Create the timeslice operator that accepts an `Expression<Date>` as an argument and does the bucketing (nontrivial)
- [ ] Add an automatic `sort by _timeslice` automatically after groupingby `_timeslice`

Proposed query structure:
```* | parse "* * *" as level, date, message | timeslice(parseDate(level)) 5m | count by _timeslice```

**Comment by tallpsmith** [comment]
this would be amazing, can be partialy done by pre-converting using `dateround` (part of `dateutils`), but if it can be added natively here that would be incredibly useful.

**Comment by tstack** [comment]
FYI, I’ve started working on this

**Comment by tstack** [comment]
> Add an automatic sort by _timeslice automatically after groupingby _timeslice

I think this is the last item remaining here.  To be clear, if the pipeline is `timeslice(ts) 1m | count by _timeslice`, you want the implicit sort to be by `_timeslice` instead of `_count` as it is now?

**Comment by rcoh** [comment]
Yeah exactly. It's strictly gravy, but it's nice if your time slices are in
order
