### ISSUE TITLE
Support parsing tabs

### ISSUE THREAD

**Issue by pickfire** [rcoh/angle-grinder#101]
It would be useful to be able to parse tabs.

For example, I have logs like:
```
 [WARNING]2020-01-01T00:00:00.000Z        1e4cd606-a550-4d41-b013-f61a4a3d959d      init_attendance no students user='kennimrod'
/aws/lambda/function-4TPZE69CJ8X7 2020/01/01/[$LATEST]e75d9ab689c4457da0a79316cf624c19 [WARNING]	2020-01-01T00:00:00.000Z	1e4cd106-a551-4d41-b313-f61a4a3d059d	init_attendance no students user='user'
```

Note that there are some tabs in between some of the parts.

I tried `ag '* | parse "* * [*]\t.*" as lambda_name, run_instance, log_level, datetime' < log` but it does not work, seemed like it does not recognize `\t`.

One solution in to process it with `sed` or `sd` to substitute the tabs first. For example, `sd \t , < log | ag '* | parse "* * [*],*,*,*" as lambda_name, run_instance, log_level, datetime, request_id, message`.

**Comment by rcoh** [comment]
Did you try putting a literal tab in the pattern? I agree this is needed either way though
