### ISSUE TITLE
NaN on functions like sum, avg, p90 ... treats numbers as strings?

### ISSUE THREAD

**Issue by ctrlbrk42** [rcoh/angle-grinder#107]
Sample input:

`{"time_local":"18/Jun/2020:09:37:45 -0400","remote_addr":"1.2.3.4","remote_user":"","request":"POST /my_url.php HTTP/2.0","status":200,"request_time":0.063,"http_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0"}`

I am new to ag, but it seems to me from my testing that the request_time above does not work when it's output as an integer.  If I quote it, ie "0.063" (literal) then when I run a function against it, I still get NaN.

`cat /var/log/nginx/site/access.json.log | agrind '* | json | count by status | avg(request_time)'`
_average
----------------
NaN

`cat /var/log/nginx/site/access.json.log | agrind '* | json | count by status'`
status        _count
----------------------------
200           1746
301           161

Am I missing something obvious here?  I even tried casting inside the agrind command, but that doesn't seem to work. Like I said, I've tried escaping the numerical output in quotes, makes no difference.

This tool looks amazing, but so far I cannot input my logs...

**Comment by ctrlbrk42** [comment]
If anyone wants to duplicate, here is my nginx log_format:

```
log_format json_combined escape=json
  '{'
    '"time_local":"$time_local",'
    '"remote_addr":"$remote_addr",'
    '"remote_user":"$remote_user",'
    '"request":"$request",'
    '"status":$status,'
#    '"body_bytes_sent":"$body_bytes_sent",'
    '"request_time":$request_time,'
#    '"upstream_addr":"$upstream_addr",'
#    '"upstream_status":"$upstream_status",'
#    '"upstream_response_time":"$upstream_response_time",'
#    '"upstream_cache_status":"$upstream_cache_status",'
#    '"uid":"$cookie_bbuserid",'
#    '"http_referrer":"$http_referer",'
    '"http_user_agent":"$http_user_agent"'
  '}';

```
I've commented out nearly everything trying to make a simple test work with agrind.

**Comment by rcoh** [comment]
I think the issue is your pipeline -- after `count by status`, there is no request time column anymore.

You may want something like `avg(request_time) by status` or just `avg(request_time)`

**Comment by ctrlbrk42** [comment]
> I think the issue is your pipeline -- after `count by status`, there is no request time column anymore.
> 
> You may want something like `avg(request_time) by status` or just `avg(request_time)` (without having `count by status` first)

Dang, I could have sworn I tried exactly that... but nope, just tried and it worked.  Or perhaps I tried it with quoted 'strings' instead of numeric values?  Maybe that would still break, and I didn't repeat the test without the quotes...

Either way, your suggestion solved it.  Thank you
