### ISSUE TITLE
Can we update Cargo.lock for 0.14.0?

### ISSUE THREAD

**Issue by herbygillot** [rcoh/angle-grinder#111]
Thank you

**Comment by rcoh** [comment]
yeah sorry -- it's pushed now. Not sure if I need to forcepush to the tag?

**Comment by herbygillot** [comment]
Force-pushing to the tag would would be great for me specifically, but I don't know how disruptive it might be to others 😅

**Comment by herbygillot** [comment]
Actually I think let's force push

**Comment by rcoh** [comment]
I'm going to yank 0.14.0 and push 0.14.1

**Comment by rcoh** [comment]
0.14.1 was published to cargo -- hopefully that fixes things for you, let me know if not

**Comment by herbygillot** [comment]
Works perfectly; thank you @rcoh. Thanks to this change, we can get this version of `angle-grinder` properly packaged for MacPorts [here](https://github.com/macports/macports-ports/pull/7939).  Closing this issue.
