### ISSUE TITLE
Math operator seems not to be working

### ISSUE THREAD

**Issue by thmd** [rcoh/angle-grinder#114]
```
echo "{\"abc\": \"100\"}"  |  agrind '* | json | abc * 2'
error: Expected an operator
  |
1 | * | json | abc * 2
  |            ^^^
  |
  = help: abc is not a valid operator
Error: Failed to parse query
```

I thought this should work or am I misunderstanding the feature?

**Comment by rcoh** [comment]
Sorry I haven't cut a release yet! Just merged the PR a few days ago.

**Comment by tstack** [comment]
> abc * 2

You also need to use the `as` operator to give the result a name, like so: `abc * 2 as def`

**Comment by thmd** [comment]
Oh! Didn't thought about that. I will either build from source or wait for a release.

Btw. this is a really great too. I have just started using it for some actual use and they were simple and familiar enough that I could write the sed/awk scripts faster than learning ankle-grinder I think in the long run I will be way faster with this. I assume that the actual pipeline would also run faster.

It's tweaking the pipeline slicing the data slightly different way, grouping by a different parameter where this would really speed things up I believe. Awk will force me to update the new column name in multiple places. And doing a group by count by multiple items, let alone percentile, well I don't know awk that well.

**Comment by rcoh** [comment]
I think angle-grinder will probably run slower than `awk` in most cases -- the core just isn't that highly optimized, but if you do it something where it's unusably slow, I'd be interested to hear about your usecase
