### ISSUE TITLE
Non greedy parsing

### ISSUE THREAD

**Issue by thmd** [rcoh/angle-grinder#115]
I don't know how impossible/hard this is. But in log files the biggest trouble I often have is that I need non greedy match or so I think.

Given a line like the following
`2020-06-14 08:00:05,898 [jobrunner] [JavaClass:221] DEBUG - [OperationX] completed for user: aUserName  time: 5499ms`

I want to parse it into date, user, time like
`'* | parse "* for user: * time: ms" as date, user, time'
`
Except somehow I want to say that the first *whitespace need to be non greedy and stop at the first space. I usually process this with sed (I know very little of scripting) where I keep removing the unwanted portion to make a sane but. It probably is doable with more complex regexp but an optional non greedy match for a particular section could be really useful.

Btw. the way I use sed to cut the unwanted is effectively
`| sed 's/ .* for user://'
`This is saying start at the first space while I want to say with parse stop at the first space.

**Comment by rcoh** [comment]
why don't you do something like this:
```
echo "2020-06-14 08:00:05,898 [jobrunner] [JavaClass:221] DEBUG -
[OperationX] completed for user: aUserName time: 5499ms" | agrind '* |
parse "* * [" as date, time | parse "user: * time: *ms" as user, time'
[date=2020-06-14]        [time=5499]        [user=aUserName]
```

**Comment by rcoh** [comment]
why don't you do something like this:
```
agrind '* | parse "* * [" as date, ts | parse "user: * time: *ms" as user, time'
```

**Comment by thmd** [comment]
Thanks. This works. Basically reading up wanted portions of lines into some temp fields that I won't used and discard. Makes a much better solution than multiple agrind call.
