### ISSUE TITLE
no longer builds on non-x86/arm architectures

### ISSUE THREAD

**Issue by q66** [rcoh/angle-grinder#124]
since switching to rustls, this will no longer build on any architectures other than x86 and arm, since `ring` is not portable

**Comment by rcoh** [comment]
indeed. Do you need `self-update` functionality? I can make that a feature so you can opt out of it.

**Comment by q66** [comment]
i don't really need anything, i noticed builds in our distro failed after some recent updates - why not just make openssl into a feature?

**Comment by q66** [comment]
that said, just disabling self-update would probably be okay too, since installing from a distro means it'll be managed via the package manager, and self-updates sound like they'd interfere with that

**Comment by rcoh** [comment]
yeah sorry, my build infrastructure dropped SSL support so I had to switch to rustls. Can take care of this in a few days (or I would accept a PR)

**Comment by q66** [comment]
i can manually patch it to use openssl again on our side, and drop the patch once it's fixed here (likely via self-update disable, as that just makes more sense for us)

just wanted to open an issue so we don't have to hold onto custom patches indefinitely
