### ISSUE TITLE
Plain text | json | csv output for aggregated data

### ISSUE THREAD

**Issue by liber-8** [rcoh/angle-grinder#126]
Hi,

thanks for this awesome tool!

Feature request: It would be nice if aggregated data could also be written in plain text, json or csv format (i.e. non-rendered).

Thanks,
Alberto

**Comment by rcoh** [comment]
totally agree! not sure when I'll get to this, but happy to accept a PR :-)

**Comment by liber-8** [comment]
I wish I could contribute but I'm not a developer.. I managed to get this running somehow by commenting out some lines (remove header and don't shorten lines from rendered output) but this is definitely not worth a PR :-)

**Comment by rcoh** [comment]
Added JSON support—this is available in v0.16.0

**Comment by liber-8** [comment]
Great news, thank you so much!
