### ISSUE TITLE
Outdated `Cargo.lock` file?

### ISSUE THREAD

**Issue by carlocab** [rcoh/angle-grinder#130]
angle-grinder is currently failing to build for Homebrew with Rust 1.49 on Apple Silicon: https://github.com/Homebrew/homebrew-core/pull/68089

It appears this is due to a stale lock file, causing `cargo install --locked` to pull in dependencies that do not work for angle-grinder on Apple Silicon. Is it possible for the `Cargo.lock` file to be updated? If this could be done with a new release, that would be especially helpful.

Related: https://github.com/Homebrew/homebrew-core/issues/68301

**Comment by richiksc** [comment]
@carlocab Looks like this should have been fixed in #131. Do we just need a new point release for Homebrew?

@rcoh Do you know when you're planning to make a new release?

**Comment by carlocab** [comment]
I've opened a PR to update the lock file that Homebrew uses: https://github.com/Homebrew/homebrew-core/pull/68729

Let's see if that helps.

**Comment by carlocab** [comment]
Thanks for the update, @rcoh! I've confirmed that the new `Cargo.lock` file enables building on Apple M1.

**Comment by rcoh** [comment]
Great, will cut a new release today–need to finish switching to GH actions from travis

**Comment by rcoh** [comment]
v0.16 has been cut—assets et al should be available in 20-30 minutes. Feel free to reopen if there are any issues.

**Comment by carlocab** [comment]
Thanks. I've opened https://github.com/Homebrew/homebrew-core/pull/69287 to update angle-grinder at Homebrew.
