### ISSUE TITLE
Be less eager to use live-updating table

### ISSUE THREAD

**Issue by RealOrangeOne** [rcoh/angle-grinder#141]
As a human, reading the table is very easy, and nice to use. However for scripting use, it's not.

Currently, adding in certain filters like `sort` force a live table, even when `--output` is specified. Removing the `sort` outputs in the correct format.

**Comment by rcoh** [comment]
this seems like a bug—we should only use the live table when the output is a tty

**Comment by RealOrangeOne** [comment]
Is it doing explicit tty detection? I was just reading the output in the terminal to test this, rather than piping it to a file. Either way yeah it might be, probably just needs to obey the `--output` flag more.

**Comment by Krishnadevi9878** [comment]
Hello good afternoon 😊

**Comment by rcoh** [comment]
Yeah it does tty detection, when you write to a file it will do the right thing

**Comment by rcoh** [comment]
fixed in the next release
