### ISSUE TITLE
Error self-updating from v0.15.0 to v0.16

### ISSUE THREAD

**Issue by vnicolici** [rcoh/angle-grinder#144]
```agrind --self-update
Checking target-arch... x86_64-unknown-linux-musl
Checking current version... v0.15.0
Checking latest released version... v0.16
Error: SemVerError: Expected dot
```
I'm guessing it's because 0.15.0 has two dots, and 0.16 just one.

**Comment by rcoh** [comment]
ah that's a bummer. I'm strongly considering deprecating the auto update functionality anyway, I had assumed no one was using it and it adds a lot of binary bloat

**Comment by vnicolici** [comment]
Yeah, I didn't intend to use it either, but it's in the installation procedure, and apparently the package downloaded initially is an older version.

**Comment by rcoh** [comment]
thanks, I just updated the README
