### ISSUE TITLE
Version v0.16 does not build with rust  >= 1.52

### ISSUE THREAD

**Issue by georgyo** [rcoh/angle-grinder#145]
Saw this on HN the other day, it's pertty amazing stuff.

It appears that the current latest tag of v0.16 does not build cleanly with either rust 1.52 or 1.53. And reports warnings in 1.51. It does build cleanly in 1.50.

the very next commit, 215a0f9888e5f381323b0cff35f40029d4a81e5a, fixes the build.

It may be a good time to cut v0.17.

**Comment by rcoh** [comment]
thanks for letting me know! v0.17.0 has been cut & released
