### ISSUE TITLE
Allow compound expressions in `where`

### ISSUE THREAD

**Issue by skeggse** [rcoh/angle-grinder#159]
I'd expect one of these to work:
```sh
agrind '* | json | where (true || true) | count'
error: expecting close parentheses
  |
1 | * | json | where (true || true) | count
  |                  ^^^^^^
  |
  = help: Insert a right parenthesis to terminate this expression
Error: Failed to parse query
```

```sh
agrind '* | json | where ((true) || (true)) | count'
error: expecting close parentheses
  |
1 | * | json | where ((true) || (true)) | count
  |                  ^^^^^^^^
  |
  = help: Insert a right parenthesis to terminate this expression
Error: Failed to parse query
```

Alas, it looks like the full expression syntax isn't supported in the `where` clause, which means chaining angle-grinder with something like `jq` is necessary for a more complete analysis experience.

**Comment by tstack** [comment]
What version are you using?  I believe this is working in the top-of-tree.

**Comment by skeggse** [comment]
Yep, this is working on default branch tip rev. Thanks!

**Comment by tstack** [comment]
Good to hear, I think the logical operators were not recognized in the older version and that was causing the strange error

**Comment by rcoh** [comment]
I'll get a release out this weekend, thanks for your patience!
