### ISSUE TITLE
Newest release is not latest

### ISSUE THREAD

**Issue by iainelder** [rcoh/angle-grinder#207]
Today the newest release is [v0.19.4 from 2024-06-01](https://github.com/rcoh/angle-grinder/releases/tag/v0.19.4). It has two Linux assets:

* `agrind-x86_64-unknown-linux-musl.tar.gz`
* ` agrind-x86_64-unknown-linux-gnu.tar.gz`.

The `latest` release is not the newest. It's [v0.19.3 also from 2024-06-24](https://github.com/rcoh/angle-grinder/releases/tag/v0.19.3). It has one Linux asset:

* `agrind-x86_64-unknown-linux-gnu.tar.gz`.

The missing "musl" variant forced me to switch to the "gnu" variant to [fix my installation script](https://github.com/iainelder/dotfiles/issues/9).

The "gnu" variant works for me, and I don't remember why I used the "musl" variant in the first instance, so I'm happy with the change.

But I'm wondering why the newest release isn't marked as `latest`.

Is there some bug fix or feature that I'm missing out on?

Thanks for all the great work on CLI data processing :-)

**Comment by rcoh** [comment]
ah I think the release failed and the didn't finalize it in the automated process. I just finalized it manually, should be set.

**Comment by iainelder** [comment]
Thanks, my script new grabs the newest release!
