### ISSUE TITLE
last version published to crates.io is 0.6.2

### ISSUE THREAD

**Issue by sanga** [rcoh/angle-grinder#31]
So cargo install ag gets you a rather old version. Would it be possibly to bump the crates package when tagging a new release? Cheers

**Comment by rcoh** [comment]
Pushed 0.7.5 to cargo. Future updates will go there as well

**Comment by sanga** [comment]
Any chance 0.13 could be published to crates.io also?

**Comment by rcoh** [comment]
Done.

**Comment by sanga** [comment]
Thanks!
