### ISSUE TITLE
Support for (or equivalent to) sumo's `parse nodrop`

### ISSUE THREAD

**Issue by akdor1154** [rcoh/angle-grinder#45]
the `parse` operator excludes nonmatching lines.
It would be useful to have a mode where instead the target fields become null or empty.

**Comment by rcoh** [comment]
Great idea! Happy to mentor someone if they want to take it on, otherwise I'll probably do it sometime in the semi near future

**Comment by rcoh** [comment]
Fixed in #49 thanks @akdor1154 !
