### ISSUE TITLE
Name of angle-grinder binary ag is the same as Silver Searcher binary ag

### ISSUE THREAD

**Issue by jfkw** [rcoh/angle-grinder#5]
angle-grinder looks interesting, thanks for releasing it. Note that the binary for the [Silver Searcher](https://geoff.greer.fm/ag/) grep tool is also named `ag`. I don't have a good recommendation to mitigate: `ag` is the sensible name for angle-grinder, and Silver Searcher is likely to remain popular, although Rust developers may be early adopters of [Ripgrep](https://github.com/BurntSushi/ripgrep) and be less likely to also use Silver Searcher, avoiding any name conflict.

**Comment by rcoh** [comment]
Yeah, thanks for noting this. For now, it's easy to just install it to a
different name for the moment if you also use the silver searcher. If I get
around to making a snap / brew package I'll revisit.

**Comment by jondot** [comment]
I seriously thought I found someone's April 1st joke. Silver searcher is super popular and `ag` is too. It's like trying to name a tool "global-robust-expert-parser" so it would fit 'grep'.
Highly suggest to swap the name, unless it really is an April fool's, of course :).

**Comment by rcoh** [comment]
Yeah not an April fool's joke. What about chop saw / cs?

**Comment by rcoh** [comment]
Renamed to agrind

**Comment by bknowles** [comment]
I notice that the documentation still refers to "ag" when installing with cargo.

Is that intentional?

**Comment by rcoh** [comment]
That's what the cargo package is called. Will rename
