### ISSUE TITLE
Boolean logic for keywords

### ISSUE THREAD

**Issue by akdor1154** [rcoh/angle-grinder#52]
(parenthesis) and `not`, `and`, and `or` (or `!`, `&&`, and `||`, or `¬`, `∧`, and `∨`, etc. etc.) would be really helpful when combining filters.

A naïve implementation of this would be backwards incompatible with the current ANDed list of filters.

**Comment by rcoh** [comment]
This should be medium-straightforward for someone with experience writing grammars. The non-grammar changes should be pretty straightforward

**Comment by akdor1154** [comment]
Yeah the one hold up was whether I try and integrate it with the current expression parser used for `where` - was going to have it independent for first implementation.

**Comment by rcoh** [comment]
Yeah that sounds good, no need to integrate

**Comment by tstack** [comment]
> Yeah the one hold up was whether I try and integrate it with the current expression parser used for where - was going to have it independent for first implementation.

Isn't the [SumoLogic search syntax](https://help.sumologic.com/05Search/Get-Started-with-Search/How-to-Build-a-Search/Keyword-Search-Expressions) quite a bit different from the syntax for expressions that operate on fields?  It doesn't seem feasible to try and merge the two.

**Comment by rcoh** [comment]
I'm working on this

**Comment by rcoh** [comment]
I merged support for `AND` `OR` and `NOT` -- It's fairly strict on requiring parenthesis at the moment, but it should meet most use cases.
