### ISSUE TITLE
Upgrade to Nom 5

### ISSUE THREAD

**Issue by rcoh** [rcoh/angle-grinder#72]
Nom 5.0 removes macros and should make the parser much easier to work on for people unfamiliar with `nom`. This is currently blocked by `nom_locate` supporting `nom` 5: https://github.com/fflorent/nom_locate/pull/23

**Comment by sanga** [comment]
FYI nom v5 is apparently in master these days: 

https://github.com/fflorent/nom_locate/blob/master/Cargo.toml

**Comment by tstack** [comment]
I’m, very slowly, working on upgrading to nom 6.

**Comment by rcoh** [comment]
Wow, that sounds like a massive effort! Feel free to investigate other
parsers like pest if you want. I know nom hasn't been the easiest to use

**Comment by tstack** [comment]
Can this be closed now?

**Comment by rcoh** [comment]
Yep!
