### ISSUE TITLE
Support Apache Combined Log format

### ISSUE THREAD

**Issue by delucks** [rcoh/angle-grinder#81]
Hey this tool is really neat! The addition of the logfmt operator made me think of another type of log file that's in common use which people would likely use `agrinder` against- Apache's Combined log format. Many other web servers, including nginx and caddy, are able to output in combined log format, so adding a parser for this format would immediately make this program useful for a variety of web server logs. Since the fields are well-defined and structured, it shouldn't be too difficult to break them up into a format that's useful for angle-grinder.

**Comment by rcoh** [comment]
interesting. For formats like this that are parsable with the existing `parser` operator I'm considering having some why of having a "parser library" so that you could write parsers like this without needing to write any Rust. Thoughts?

**Comment by delucks** [comment]
@rcoh, that sounds like a great idea! Having a separate method to create a parser without writing Rust would make it easier for folks like me to contribute to the project in a meaningful technical way. Plus, people could try out other formats locally before submitting them upstream.
