### ISSUE TITLE
Truncated output when sorting

### ISSUE THREAD

**Issue by DarrenTsung** [rcoh/angle-grinder#90]
Weird thing happened when I tried to parse this file (https://gist.github.com/DarrenTsung/be52ede5c7deb46e24297ce75c10b704) with the query:
```
* | parse '*Oct*' as num, date | sort date desc
```

The sort seems to be missing rows (specifically lines with dates on the minute 09:49). However, when I remove the `sort date desc`, all the lines appear as normal.

Other weird thing is I put it in an integration test and it works fine, but running this locally:
```
cargo run -- -f weird.txt "* | parse '*Oct*' as num, date | sort date desc"
```
still has the truncated behavior. I also tried:
```
cat weird.txt | cargo run -- "* | parse '*Oct*' as num, date | sort date desc"
```

Any idea what could be going on here? I think I've seen this behavior before (truncation on sort). 

Maybe there's something weirdly configured with my terminal?
- Just tried it in default terminal, same behavior.

**Comment by rcoh** [comment]
When rendering to the terminal, sort will only display as many rows as will
fit. Try rendering to a file (>)

This happens with all aggregate operators and is a side effect of the magic
to be able to update things on the terminal.

It wouldn't be unreasonable to not truncate the last row...

**Comment by DarrenTsung** [comment]
Oh okay, makes sense. Thanks for the quick response!
